server:
  workers: 3
  node:
    environment: production
    dataDir: /presto/data
    pluginDir: /presto/plugin
  log:
    presto:
      level: DEBUG
  config:
    path: /presto/etc
    http:
      port: 8080
    query:
      maxMemory: "4GB"
      maxMemoryPerNode: "1GB"
  jvm:
    maxHeapSize: "8G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"
  catalog:
    data:
      pulsar.properties: |
        connector.name=pulsar
        pulsar.broker-service-url=http://pulsar-1-broker.pulsar-1.svc.cluster.local:8080
        pulsar.zookeeper-uri=pulsar-1-zookeeper.pulsar-1.svc.cluster.local:2181
        pulsar.target-num-splits=4

image:
  repository: oginskis/prestodb
  tag: 0.206
  pullPolicy: IfNotPresent
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

service:
  type: LoadBalancer

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
